### ISSUE TITLE
Colorbar should use lines map

### ISSUE THREAD

**Issue by okomarov** [okomarov/schemaball#3]
Colorbar should use generated map, not the matlab default.

**Comment by okomarov** [comment]
@rb643 The colorbar issues should be fixed

**Comment by rb643** [comment]
Thanks! It does now, though the scale still seems off? I'm plotting a matrix with negative values and the scale ranges from 0-1 rather than -1 to 1. Any thoughts on that?

**Comment by okomarov** [comment]
Can you please provide an example (code)?

**Comment by rb643** [comment]
Hi Oleg,

Attached is an example of the type of matrix I'm trying to plot with the accompanying names.

Cheers,

Richard
________________________________

**Comment by okomarov** [comment]
@rb643 Email attachments don't go through. Maybe you want to post under [this issue](https://github.com/okomarov/schemaball/issues/5) or one of the other two, whichever fits better your problem, since this particular issue has been solved.
